### PR TITLE
javascript //region

### PR DESCRIPTION
**Pull request by BernsteinA**

### CODE REVIEW

**Comment by Hirse** [comment]
Thanks for your PR. Some questions before I merge though:
What does `//region` mean?
Why does your PR change the whole `JavaScript.js` and `style.css` files?

**Comment by BernsteinA** [comment]
//region is for organising and folding sections of code.

Not sure why it appears to change the whole files. Line endings maybe. What
diff tool are you using?

**Comment by Hirse** [comment]
Just looking at it in GitHub.

**Comment by BernsteinA** [comment]
close this PR and I'll clean my repo up; will submit a new PR with more sane looking differences

**Comment by Hirse** [comment]
Thanks. 
Please also include a short description of Haxe as I never heard of it. ;)

**Comment by BernsteinA** [comment]
@Hirse http://haxe.org/

**Comment by Hirse** [comment]
Alright, could you include a test file in your PR? See the test folder with files for Python etc.

**Pull request closed without merging**
