### PR TITLE
Proposal for #57: PHP parser.

### LINKED ISSUE #42: Problem with PHP function declaration that span multiple lines
Hello, 
when a create a function/method in class in the Bracket, the output outline don’t show correctly function

capture
ex :
```php
class myClass{
    private function myFunc(
        $arg1      = null
        $other     = null
    ){…}
    …
}
```

### PR DESCRIPTION
**Pull request by yfwz100**
I drafted a simple parser using [lex](https://www.npmjs.com/package/lex). I don't know how to include such dependency so I just created a file in `thirdparty` folder. 

This proposal is for #57 and it seems to fix #42 .

### CODE REVIEW

**Comment by Hirse** [comment]
That sounds great. Thanks for your contribution.

Before I merge, could you add a few comments and explanations to your parser function so I am going to be able to understand and expand this when required?

**Comment by yfwz100** [comment]
It's a state machine defined via [lex](https://www.npmjs.com/package/lex). The main component of the modification is the `parse()` method. `parse()` method parse the source text: when it came across keyword(`function`/`class`/`(`/`)`/`{`/`}`), it stores the identity word hierarchically.

**Comment by yfwz100** [comment]
I add some comments on the code. @Hirse

**Comment by Hirse** [comment]
@yfwz100, I have modified your code a little bit and started with adding tests for it.
If you feel like helping out some more, more tests are always welcome. :wink:

**Comment by yfwz100** [comment]
The code structure is nice :smile: . I am glad to help improve this plugin if I have time. It's really nice to show the meaningful code structure when navigating in a large file.

**Pull request merged**
